#Imagem Docker base que será utilizada na criação da imagem
FROM ubuntu

#Indicar o mantenedor da imagem Docker
MAINTAINER diegokalschne

#Para atualizar a lista de pacotes do Ubuntu
RUN apt-get -y update

#Para instalar o Node.js
RUN apt-get -y install nodejs