apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-custom-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx-custom
  template:
    metadata:
      labels:
        app: nginx-custom
    spec:
      containers:
      - name: nginx
        image: nginx-dual-site:1.0
        ports:
        - containerPort: 8080
        - containerPort: 9090