version: "3.7"

services:

  caddy:
    image: caddy:2.6
    restart: unless-stopped
    ports:
      - "50000:80"
      - "54443:443"

    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./site:/srv
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
