FROM caddy:latest

LABEL maintainer="Leonardo <leonardo.ojczenasz@sou.unijui.edu.br>"

# Exposicao da porta padrão do Caddy
EXPOSE 80 443

# Comando padrão para iniciar o servidor Caddy
CMD ["caddy", "run", "--config", "/etc/caddy/Caddyfile"]

