#Imagem Docker base da criação da imagem		
FROM ubuntu
#Mantenedor da imagem docker
MAINTAINER guilhermesaueressig
#Atualizar a lista de pacotes do Ubuntu
RUN apt-get -y update
#Instalar o Python
ENV apt-get -y install python
